# Metadata
title: "IDIS 2020: Art of the Living Web"
description: "A course on interactive web design"
keywords: ["glitch", "jekyll"]

# Third party services
# (Anything you put here will be public!)
google-analytics: 

# Build settings
encoding: utf-8
markdown: kramdown
exclude:
  - .sass-cache/
  - node_modules/
  - .gitignore
  - Gemfile
  - _config.yml
  - glitch.json
  - package.json
  - package-lock.json
  - watch.json
  - "*.save.*"